apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: danuri-stage

resources:
- ../../base
- doppler-secret.yaml

images:
- name: ghcr.io/danuri-team/potato4cut-v2-backend
  newTag: 3ba64d5e

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
- path: potato-4cut-stage-route.yaml
  target:
    kind: HTTPRoute
