apiVersion: apps/v1
kind: Deployment
metadata:
  name: potato-4-cut
spec:
  replicas: 1
  template:
    spec:
      tolerations:
        - key: "oci.oraclecloud.com/oke-is-preemptible"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: potato-4-cut
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
          envFrom:
            - secretRef:
                name: potato-4-cut-stage
