apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: potato-4-cut-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: stg.potato-4cut-api.mya.ong
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: potato-4-cut
                port:
                  number: 80
  tls:
    - hosts:
        - stg.potato-4cut-api.mya.ong
      secretName: danuri-api-tls