apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: danuri-prod

resources:
- deployment.yaml
- bmo-prod.yaml

images:
- name: danuri-team/bmo
  newTag: 1fdeeadd
- name: ghcr.io/danuri-team/bmo
  newTag: latest
