apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: danuri-prod

resources:
- ../../base
- doppler-secret.yaml

images:
- name: ghcr.io/danuri-team/potato4cut-v2-backend
  newTag: b9909e4b

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
